### ISSUE TITLE
Debian 7, wxpython package choices.

### ISSUE THREAD

**Issue by imstanz** [Kiv/poclbm#111]
Following Linux Source Instructions, I get error:
          Traceback (most recent call last):
            File "./guiminer.py", line 15, in <module>
              import wx
          ImportError: No module named wx

Getting python2.7 seemed pretty straight forward..
As for wxPython - debian offers different package names, I didn't want to just install anything...so I ask which one?
python-wxglade
python-wxtools (installed)
python-wxversion (installed)
python-wxgtk2.8 (I installed and guiminer loaded)
python-wxmpl
wx2.8-examples (I installed)

As I typed this-I recieved error- then installed python-wxgtk2.8, then gui ran! 
Click 'start mining', Exter flags: -f 60 (per instructs)
- ImportError: No modules named serial.tools
  Not mining at present.

So maybe this is a help rather then issue.
Thanks ~

**Comment by imstanz** [comment]
2014-04-07 14:30:06: Listener for "Default" shutting down
2014-04-07 14:30:18: Running command: python poclbm.py downwithgov.2:x@marks:17777 --device=0 --platform=0 --verbose -r1 -f 60
2014-04-07 14:30:18: Listener for "Default" started
2014-04-07 14:30:19: Listener for "Default": WARNING: no adl3 module found (github.com/mjmvisser/adl3), temperature control is disabled
2014-04-07 14:30:19: Listener for "Default": Traceback (most recent call last):
2014-04-07 14:30:19: Listener for "Default": File "poclbm.py", line 84, in <module>
2014-04-07 14:30:19: Listener for "Default": import BFLMiner
2014-04-07 14:30:19: Listener for "Default": File "/home/user/Desktop/Miners/poclbm-master/BFLMiner.py", line 4, in <module>
2014-04-07 14:30:19: Listener for "Default": from ioutil import find_udev, find_serial_by_id, find_com_ports
2014-04-07 14:30:19: Listener for "Default": File "/home/user/Desktop/Miners/poclbm-master/ioutil.py", line 2, in <module>
2014-04-07 14:30:19: Listener for "Default": from serial.tools import list_ports
2014-04-07 14:30:19: Listener for "Default": ImportError: No module named serial.tools
2014-04-07 14:32:48: Listener for "Default" shutting down

**Comment by JULIETPAPA** [comment]
I thought I was joining a mining pool.  Can anyone help me understand all of this.  I am willing to take classes if anyone knows of any.  I would love to find out why I received these messages.  If you can help make sense of any of this, feel free to drop a line.
