### ISSUE TITLE
Missing logo?

### ISSUE THREAD

**Issue by ghost** [Kiv/poclbm#3]
When starting the GUI, I get a modal error:

"can't open file 'logo.ico' (error 2: No such file or directory)

I am sure it's there, the logo file, just not sure why I get the error. In addition, the system tray con is a blank white square. I assume that is due to the offending file.

**Comment by Kiv** [comment]
Any more details? Is this Windows or Linux? Is the file actually there on your system? Are you using the binary or running from source?

**Comment by ghost** [comment]
Debian Linux, I pulled the source down from git. Yes, there is a logo there in the directory but it does not show up. I even tried changing the logo image, thinking it may not have liked the one you had there. (Long shot)

**Comment by displague** [comment]
Also a problem on OSX:

mjohansson@yeahyeah:~/Applications/poclbm$ python2.7 guiminer.py 
ERROR:root:Failed to load taskbar icon; continuing.
ERROR:root:Exception:
Traceback (most recent call last):
  File "guiminer.py", line 2121, in run
    frame_1 = GUIMiner(None, -1, "")
  File "guiminer.py", line 1579, in **init**
    self.set_properties()
  File "guiminer.py", line 1622, in set_properties
    self.SetIcons(get_icon_bundle())
  File "guiminer.py", line 171, in get_icon_bundle
    return wx.IconBundleFromFile("logo.ico", wx.BITMAP_TYPE_ICO)
  File "/usr/local/lib/wxPython-2.9.1.1/lib/python2.7/site-packages/wx-2.9.1-osx_cocoa/wx/_gdi.py", line 1449, in IconBundleFromFile
    val = _gdi_.new_IconBundleFromFile(_args, *_kwargs)
PyAssertionError: C++ assertion "icon.IsOk()" failed at /BUILD/wxPython-src-2.9.1.1/src/common/iconbndl.cpp(249) in AddIcon(): invalid icon
Traceback (most recent call last):
  File "guiminer.py", line 2130, in <module>
    run()
  File "guiminer.py", line 2121, in run
    frame_1 = GUIMiner(None, -1, "")
  File "guiminer.py", line 1579, in **init**
    self.set_properties()
  File "guiminer.py", line 1622, in set_properties
    self.SetIcons(get_icon_bundle())  
  File "guiminer.py", line 171, in get_icon_bundle
    return wx.IconBundleFromFile("logo.ico", wx.BITMAP_TYPE_ICO)  
  File "/usr/local/lib/wxPython-2.9.1.1/lib/python2.7/site-packages/wx-2.9.1-osx_cocoa/wx/_gdi.py", line 1449, in IconBundleFromFile
    val = _gdi_.new_IconBundleFromFile(_args, *_kwargs)
wx._core.PyAssertionError: C++ assertion "icon.IsOk()" failed at /BUILD/wxPython-src-2.9.1.1/src/common/iconbndl.cpp(249) in AddIcon(): invalid icon

I'll try the fork that's floating around with the icon fix and report back.

**Comment by Kiv** [comment]
I believe this issue is fixed with commit d71016105ea5b11f0eaa which uses an absolute path for the icon rather than relative path. 

Several Windows users reported that this fix worked for them. Please re-open it if you're still encountering it on Linux.
