### ISSUE TITLE
HTTPS omission

### ISSUE THREAD

**Issue by Maeslin** [Kiv/poclbm#37]
seems Slush's pool started mandating HTTPS for the API. Here's a potential fix?

from:
    def requires_https(self, host):
        """Return True if the specified host requires HTTPs for balance update."""
        return host == "mtred.com"

to:
    def requires_https(self, host):
        """Return True if the specified host requires HTTPs for balance update."""
        HOSTS_REQUIRING_HTTPS = ["mtred.com",
                                 "api2.bitcoin.cz"]
        if host in HOSTS_REQUIRING_HTTPS: return True
        return False

Bear with me, I've got no experience with Python. Can't run it from source for some reason, attempting it gives me

Traceback (most recent call last):
  File "D:\guiminer\guiminer.py", line 13, in <module>
    import sys, os, subprocess, errno, re, threading, logging, time, httplib, urllib
  File "C:\Python27\lib\httplib.py", line 71, in <module>
    import socket
  File "C:\Python27\lib\socket.py", line 47, in <module>
    import _socket
ImportError: DLL load failed: %1 is not a valid Win32 application.

and I can't quite figure out what I'm missing. Fresh installation of Python 2.7.2 and wxPython.

**Comment by berossm** [comment]
HTTPS api calls are now also required for BTC Guild.  The http calls are currently returning a 302 (not sure how long that is intended to remail functional) So another opption would be to update api requests to include the ability to follow 302's

I don't have python installed at this time so I can't contribute any thoughts to actaual fixes at this time.
