### ISSUE TITLE
Connection problems with new release of poclbm

### ISSUE THREAD

**Issue by colindean** [Kiv/poclbm#51]
In the console window, when I've replaced the poclbm.exe from 2012-02-19 packaged with GUIMiner of the same date with the poclbm.exe from yesterday's release (2012-09-20).

```
2012-09-21 17:45:26: Listener for "6850" started
2012-09-21 17:45:26: Listener for "6850": 21/09/2012 17:45:26, need more than 1 value to unpack
2012-09-21 17:45:26: Listener for "6850": Traceback (most recent call last):
2012-09-21 17:45:26: Listener for "6850": File "poclbm.py", line 85, in <module>
2012-09-21 17:45:26: Listener for "6850": File "BitcoinMiner.pyo", line 50, in __init__
2012-09-21 17:45:26: Listener for "6850": File "BitcoinMiner.pyo", line 263, in get_adapter_info
2012-09-21 17:45:26: Listener for "6850": NameError: global name 'ADLError' is not defined
```

**Comment by colindean** [comment]
It looks like the problem may actually be more in poclbm in BitcoinMiner.py:263. ADLError is not imported on [line 16](https://github.com/m0mchil/poclbm/blob/master/BitcoinMiner.py#L16) with the rest of the ADL stuff.

**Comment by Kiv** [comment]
I'm releasing a GUIMiner update in the next couple days with the latest poclbm, so this should be fixed then.
