### ISSUE TITLE
Can't save config

### ISSUE THREAD

**Issue by maitredede** [Kiv/poclbm#75]
Hi,

I'm using GUIMiner v2012-12-03

When I click "Save parameters", nothing happen. When I try to quit, "Do you want to save ?" => "Yes", nothing happen.

Where should I start digging ? Thanks

**Comment by Grawl** [comment]
Accept. It does not work for me too. Nothing happen there.

**Comment by techman05** [comment]
Seems to work for me but I'm using the one from guiMiner.com I'm on windows 7sp1 and vista sp >1 . I just to have to every time I change something major have to delete the file and remake it. It  misses some of the parenthasises when its saved over an original.

**Comment by pvodicka** [comment]
Not 100% sure but it seems to be related to problem with unicode characters in Windows user name (so in config saving path)...
Traceback (most recent call last):
  File "guiminer.py", line 2028, in on_close
  File "guiminer.py", line 2056, in save_config
  File "json__init__.pyo", line 231, in dumps
  File "json\encoder.pyo", line 201, in encode
  File "json\encoder.pyo", line 264, in iterencode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe8 in position 19: invalid continuation byte
