### ISSUE TITLE
Long poll IO error timeout

### ISSUE THREAD

**Issue by mike-hart** [Kiv/poclbm#76]
eu.eclipsemc.com:8337 13/04/2013 16:27:53, long poll IO error timed out
Traceback (most recent call last):
  File "GetworkSource.pyo", line 198, in long_poll_thread
  File "GetworkSource.pyo", line 105, in request
  File "httplib.pyo", line 958, in request
  File "httplib.pyo", line 992, in _send_request
  File "httplib.pyo", line 954, in endheaders
  File "httplib.pyo", line 814, in _send_output
  File "httplib.pyo", line 776, in send
  File "httplib.pyo", line 757, in connect
  File "socket.pyo", line 571, in create_connection
timeout: timed out
eu.eclipsemc.com:8337 13/04/2013 16:27:53, LP connected to eu.eclipsemc.com:8337

Sadly I have no idea _why_ this happens, just that it does. There appears to be recovery when this error occurs when running poclbm in DOS console, not sure if it will have other issues with the guiminer parser.

**Comment by mike-hart** [comment]
Moved to m0mchil's poclbm, sorry for opening on wrong project.
