### ISSUE TITLE
long poll IO error Traceback

### ISSUE THREAD

**Issue by mike-hart** [Kiv/poclbm#77]
eu.eclipsemc.com:8337 13/04/2013 16:30:31, long poll IO error
Traceback (most recent call last):
  File "GetworkSource.pyo", line 198, in long_poll_thread
  File "GetworkSource.pyo", line 106, in request
  File "GetworkSource.pyo", line 144, in timeout_response
  File "httplib.pyo", line 1018, in getresponse
ResponseNotReady
eu.eclipsemc.com:8337 13/04/2013 16:30:31, LP connected to eu.eclipsemc.com:8337

Sadly I have no idea _why_ this happens, just that it does. There appears to be recovery when this error occurs when running poclbm in DOS console, not sure if it will have other issues with the guiminer parser.

**Comment by mike-hart** [comment]
Moved to m0mchil's poclbm, apologies for opening on wrong fork.
