### ISSUE TITLE
Tracebacks when network connection lost

### ISSUE THREAD

**Issue by mike-hart** [Kiv/poclbm#79]
eu.eclipsemc.com:8337 13/04/2013 17:12:17, long poll IO error [Errno 10061] No connection could be made because the target machine actively refused it
Traceback (most recent call last):
  File "GetworkSource.pyo", line 198, in long_poll_thread
  File "GetworkSource.pyo", line 105, in request
  File "httplib.pyo", line 958, in request
  File "httplib.pyo", line 992, in _send_request
  File "httplib.pyo", line 954, in endheaders
  File "httplib.pyo", line 814, in _send_output
  File "httplib.pyo", line 776, in send
  File "httplib.pyo", line 757, in connect
  File "socket.pyo", line 571, in create_connection
error: [Errno 10061] No connection could be made because the target machine actively refused it

This is repeated over and over when a network connection is lost. Maybe poclbm should start (and notify about) an exponential backoff rather than just continuing to spam the logs every ~3s when connection is lost?

**Comment by mike-hart** [comment]
Reopened on poclbm, apologies.
