### ISSUE TITLE
guiminer cannot start mining if I start it from command line

### ISSUE THREAD

**Issue by linkstack** [Kiv/poclbm#91]
If I start guiminer from command line and click "start mining" button, nothing happens.
And when I close guiminer, it pops up a message box saying "it has written error message to guiminer.exe.log"

Following is the traceback from guiminer.exe.log:

> Traceback (most recent call last):
>   File "guiminer.py", line 860, in toggle_mining
>   File "guiminer.py", line 1008, in start_mining
>   File "subprocess.pyo", line 672, in **init**
>   File "subprocess.pyo", line 787, in _get_handles
>   File "subprocess.pyo", line 826, in _make_inheritable
> WindowsError: [Error 6]

**Comment by rawsp33d** [comment]
I have the first problem but not the second.
