### ISSUE TITLE
Current files don't see openCL devices

### ISSUE THREAD

**Issue by techman05** [Kiv/poclbm#95]
It looked like a lot of items had been updated and I tried to run with the packages needed via python 2.7 installed and packages from portable python 2.7 . I find myself with an error saying it can't find openCL devices and that there are depreciated items like "initAllImageHandlers"

I'm hoping if its the case you are using below 2.7 that it can be updated to it or beyond. 

Also hopefully there can be more written on how to open from github and start pooling.and/or from gui or command line (command line call to guiminer.py is as far as I've gotten.).

Thanks

**Comment by techman05** [comment]
Just noticed that the download from here still pulls up the gui for 12/3/2012 when the screenshots don't show the date for the new one.

Also the icon doesn't show up though I found the program does load but still with no openCL devices

Hope this helps

**Comment by ashes1601** [comment]
i cant figure how to use this at all i need to visual y see someone set it up like the minner on my page when u first pull it up ther is four blank spaces what do u put in each on e 

Date: Tue, 23 Jul 2013 10:27:45 -0700

**Comment by techman05** [comment]
Mine loaded to a tray icon with no icon. That's where I found the gui. I downloaded the whole git directory as a zip so it came with the screenshot folders.  If you have them and this working(without my error above), it should be easy to setup though you may need to use the "other" tab to fill in some servers not listed.

I think I need to find the appdata folder where guiminer opens and clear the old version from it(python hasn't come up yet) to try this version.

**Comment by techman05** [comment]
I found this while trying to see if it was just that it was not compiled an missing a file and this was in setup.py

 # OpenCL.dll is vendor specific
      options=dict(py2exe=dict(
          dll_excludes=['OpenCL.dll', 'w9xpopen.exe'],
          compressed=True,
          optimize=2,
          excludes = ["Tkconstants", "Tkinter", "tcl", "curses", "_ssl", "pyexpat", "unicodedata", "bz2"],
      )), 

This was my other thought that goes back, is it not on the git.hub package or messed up with the bfl code. Theres 2 files labeled opencl in the compiled version its looking for it can't find I think.

2013-07-28 23:43:46: Listener for "btc" started
2013-07-28 23:43:48: Listener for "btc": No PyOpenCL
2013-07-28 23:43:48: Listener for "btc": Not using OpenCL
2013-07-28 23:43:48: Listener for "btc": Traceback (most recent call last):
2013-07-28 23:43:48: Listener for "btc": File "poclbm.py", line 84, in <module>
2013-07-28 23:43:48: Listener for "btc": import BFLMiner
2013-07-28 23:43:48: Listener for "btc": File "C:\Users\bla\Desktop\guiCompileFiles\poclbm-master\BFLMiner.py", line 4, in <module>
2013-07-28 23:43:48: Listener for "btc": from ioutil import find_udev, find_serial_by_id, find_com_ports
2013-07-28 23:43:48: Listener for "btc": File "C:\Users\bla\Desktop\guiCompileFiles\poclbm-master\ioutil.py", line 2, in <module>
2013-07-28 23:43:48: Listener for "btc": from serial.tools import list_ports
2013-07-28 23:43:48: Listener for "btc": ImportError: No module named tools

Are these files I can pull from the current compile or can you add them in so I can try and run from github files?

**Comment by ashes1601** [comment]
i have no idea what u mean at all 

Date: Sun, 28 Jul 2013 20:58:07 -0700

**Comment by techman05** [comment]
I was more noting it toward my issue of "OPENCL not DETECTING DEVICES". You should probably make a new issue. I'm hoping @Kiv sees some of these issues and knows how to make it work.

**Comment by techman05** [comment]
I might have found a stupid reason why uncompiled isn't working. I have the packages and not the installations for numpy and pyopencl which are required to run openCL.

Here are the links I think I found (but have not tested yet for these installation)
http://sourceforge.net/projects/numpy/files/NumPy/1.7.1/
and
http://wiki.tiker.net/PyOpenCL/Installation/Windows

Maybe if these aren't the correct links they can be added to the "Whats needed" section and what version is verified for guiMiner.

**Comment by techman05** [comment]
@Kiv Wat version do I need of these file? Numpy can't see 3.3  and pyopencl is installed for both and the sdk for amd for opencl and the nvida version are installed. I don't know if your calling the packages from python or if there is supposed to be a physical installation for the required files.

Maybe you can add some more info to what version is expected and where guiMiner is being extracted to run ,since I have the compiled one and that may be fudging me too.

Thanks
